name: Documentation
description: Report an issue or suggest an improvement to the documentation
title: "[Docs]: "
labels: ["documentation"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs make the project better for everyone.

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      description: What kind of documentation issue is this?
      options:
        - Typo or grammatical error
        - Outdated information
        - Missing documentation
        - Unclear or confusing
        - Broken link
        - Code example not working
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: "e.g., README.md, docs/getting-started.md, API reference, etc."
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL (if applicable)
      description: Link to the documentation page if it's hosted online
      placeholder: "https://..."
    validations:
      required: false

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say? (Quote or describe the relevant section)
      placeholder: Paste or describe the current content...
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: What's Wrong?
      description: Describe what's incorrect, missing, or unclear
      placeholder: Explain the issue with the current documentation...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be changed? Provide suggested text if possible.
      placeholder: Describe or write out your suggested changes...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this?
      options:
        - label: I'm willing to submit a pull request to fix this documentation
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: Any additional information...
    validations:
      required: false
